Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Стандартное импортирование plotly
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot

# Использование cufflinks в офлайн-режиме
import cufflinks
cufflinks.go_offline()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m [38;5;66;03m# Стандартное импортирование plotly[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplotly[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpy[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgraph_objs[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgo[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01moffline[39;00m [38;5;28;01mimport[39;00m iplot

File [0;32m/opt/anaconda3/lib/python3.8/site-packages/plotly/plotly/__init__.py:4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m__future__[39;00m [38;5;28;01mimport[39;00m absolute_import
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01m_plotly_future_[39;00m [38;5;28;01mimport[39;00m _chart_studio_error
[0;32m----> 4[0m [43m_chart_studio_error[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mplotly[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/anaconda3/lib/python3.8/site-packages/_plotly_future_/__init__.py:43[0m, in [0;36m_chart_studio_error[0;34m(submodule)[0m
[1;32m     42[0m [38;5;28;01mdef[39;00m [38;5;21m_chart_studio_error[39m(submodule):
[0;32m---> 43[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     44[0m         [38;5;124;03m"""[39;00m
[1;32m     45[0m [38;5;124;03mThe plotly.{submodule} module is deprecated,[39;00m
[1;32m     46[0m [38;5;124;03mplease install the chart-studio package and use the[39;00m
[1;32m     47[0m [38;5;124;03mchart_studio.{submodule} module instead. [39;00m
[1;32m     48[0m [38;5;124;03m"""[39;00m[38;5;241m.[39mformat(
[1;32m     49[0m             submodule[38;5;241m=[39msubmodule
[1;32m     50[0m         )
[1;32m     51[0m     )

[0;31mImportError[0m: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 


